version: "3.5"
networks:
  default:
    name: universal-resolver
services:
  uni-resolver-web:
    image: universalresolver/uni-resolver-web:latest
    ports:
      - "8080:8080"
  driver-did-sov:
    image: universalresolver/driver-did-sov:latest
    environment:
      uniresolver_driver_did_sov_libIndyPath: ${uniresolver_driver_did_sov_libIndyPath}
      uniresolver_driver_did_sov_poolConfigs: "_;./sovrin/bcovrin-test.txn"
      uniresolver_driver_did_sov_poolVersions: ${uniresolver_driver_did_sov_poolVersions}
      uniresolver_driver_did_sov_walletName: ${uniresolver_driver_did_sov_walletName}
    ports:
      - "8082:8080"
